### ISSUE TITLE
hclust-lw returns nil for some nodes

### ISSUE THREAD

**Issue by jandot** [lerouxrgd/clj-hclust#1]
Found 2 issues with hclust-lw, that might be related. In many cases, the **hclust-lw function returns a nil** where it should return a node. As a result, some nodes are not represented in the final tree visualization. For some example code with output, see this gist: [https://gist.github.com/jandot/99509f603d3335a84671](https://gist.github.com/jandot/99509f603d3335a84671). In addition, this function sometimes returns a **NullPointerException**. See the same gist for a full stack trace.

**Comment by lerouxrgd** [comment]
Just saw your issue.
Thanks for pointing that out.
Looks like clust-id function and (:merged state) don't keep track of merged clusters ids correctly.
I will investigate that.

**Comment by lerouxrgd** [comment]
Fixed it on master, let me know if it works for you too.
If everything is fine I will release 0.1.1 on clojars.

**Comment by jandot** [comment]
Thanks. I'll have a look.

j.
